Project_Final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings
from landing.views import HomeView
from product.views import product_list_api, category_list_api, productListApi, productDetailApi

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('', include('landing.urls'), name='landing'),
    path('product/', include('product.urls'), name='product'),
    path('customer/', include('customer.urls'), name='customer'),
    path('order/', include('order.urls'), name='order'),
    # serializers
    # path('product/', product_list_api),
    # path('product_list/', productListApi.as_view()),
    # path('product_Detail/<int:pk>', productDetailApi.as_view()),
    # path('category/', category_list_api),
    prefix_default_language=True
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/urls.py
from django.urls import path

from .views import HomeView, LoginView, registerView, LogoutView,profileView

app_name = 'landing'
urlpatterns = [
    path('', HomeView.as_view(),name ='Home'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', registerView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', profileView.as_view(), name='profile'),
]

order/urls.py
from django.urls import path
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from order.views import OrderViewSets, Order_itemViewSets, card_list, \
    Order_items_sessionDeleteView, Order_itemsUpdate_sessionView, card_list_orderView, order_items_update_Api, \
    order_items_delete_Api, Order_delivery, Order_cancel

router = DefaultRouter()
router.register('Order', OrderViewSets, basename='Order')
router.register('Order_item', Order_itemViewSets, basename='Order_item')
app_name = 'order'
urlpatterns = [
    path('', include(router.urls)),
    path('delete_order_item/<int:pk>', order_items_delete_Api.as_view(), name='delete_order_item'),
    path('delete_order_item_session/<int:pk>', Order_items_sessionDeleteView.as_view(),
         name='delete_order_item_session'),
    path('update_order_item/<int:pk>', order_items_update_Api.as_view(), name='update_order_item'),
    path('update_order_item_session/<int:pk>', Order_itemsUpdate_sessionView.as_view(),
         name='update_order_item_session'),
    path('card_list/', card_list.as_view(), name='card_list'),
    path('card_list_order/', card_list_orderView.as_view(), name='card_list_order'),
    path('Order_delivery/<int:pk>', Order_delivery.as_view(), name='Order_delivery'),
    path('Order_cancel/<int:pk>', Order_cancel.as_view(), name='Order_cancel'),
]

product/urls.py
from django.urls import path

from .views import product_for_categoryListview, ProductDetailView,add_to_OrderView

app_name = 'product'
urlpatterns = [
    # path('Category/', CategoryListview.as_view(), name='category'),
    # path('product/', productListview.as_view(), name='product'),
    path('category_product/<int:pk>', product_for_categoryListview.as_view(), name='category_product'),
    path('Detail_product/<int:pk>', ProductDetailView.as_view(), name='Detail_product'),
    path('add_product/<int:pk>', add_to_OrderView.as_view(), name='add_product'),
]

landing/models.py
from django.db import models

# Create your models here.

landing/views.py
from django.contrib.auth.models import Permission, ContentType
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render
from django.contrib import messages
# Create your views here.
from django.views.generic import TemplateView
from django.views import View

from core.models import User
from customer.forms import CustomerForm
from customer.models import Customer


class HomeView(TemplateView):
    template_name = "landing/public/Home.html"


class registerView(View):
    form_class = CustomerForm
    # template_name = 'public/register'

    def get(self, request):
        form = CustomerForm()
        return render(request, 'landing/public/register.html', {'form': form})

    def post(self, request):
        phone = request.POST['phone']
        email = request.POST['email']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        for i in User.objects.all():
            if i.phone == phone:
                messages.add_message(request, messages.ERROR, "phone is exist")
                return render(request, 'landing/public/register.html', {'form': self.form_class})
        if password2 != password1:
            messages.add_message(request, messages.ERROR, "your password not equal")
            return render(request, 'landing/public/register.html', {'form': self.form_class})
        if len(password1) < 8:
            messages.add_message(request, messages.ERROR, "your password should more than 8")
            return render(request, 'landing/public/register.html', {'form': self.form_class})
        new_user = User.objects.create_user(username=phone, email=email,
                                            first_name=first_name, last_name=last_name, password=password1, phone=phone)
        Customer.objects.create(user=new_user)
        # code add permission see-profile in terminal
        # content_type = ContentType.objects.get_for_model(User)
        # permission = Permission.objects.create(
        #     name='can see profile',
        #     codename='see_profile',
        #     content_type=content_type
        # )
        # add permission when register
        content_type = ContentType.objects.get_for_model(User)
        permission = Permission.objects.get(content_type=content_type, codename='see_profile')
        new_user.user_permissions.add(permission)
        return render(request, 'landing/public/Login.html')


class LoginView(View):
    def get(self, request):
        # if request.session.get('uid', None) is None:
        return render(request, 'landing/public/Login.html')

    def post(self, request):
        phone = request.POST['phone']
        password = request.POST['password']

        user = User.objects.get(phone=phone)
        if not user.check_password(password):
            messages.add_message(request, messages.ERROR, "your password wrong")
            return render(request, 'landing/public/Login.html')
        request.session['uid'] = user.id
        from product.Cart import Cart
        from order.order_item_add import Order_User
        cart = Cart(request)
        user = Order_User(user)
        user.add_session(cart)
        len_order_user = user.get_user()
        cart.clear()  # remove session cart
        # set cookie
        user = {
            'user': user,
        }
        response = render(request, 'landing/public/Home.html', context=user)
        response.set_cookie('count', len_order_user[3])

        return response


class LogoutView(View):

    def get(self, request):
        if request.session.get('uid', None) is None:
            return render(request, 'landing/public/Home.html')
        del request.session['uid']
        response = render(request, 'landing/public/Home.html')
        response.delete_cookie('count')
        return response


class profileView(View):
    # permission_required = "landing.see_profile"

    def get(self, request):
        user = User.objects.get(id=request.session.get('uid', None))
        user = {
            'user': user

        }

        return render(request, 'landing/public/profile.html', context=user)

templates/landing/base/_base.html
{% load static %}
{% load i18n %}
<!doctype html>
{% get_current_language as CUREENT_LANG %}
<html lang="{{ CUREENT_LANG }}" dir="{% if CUREENT_LANG == 'fa' %}rtl{% else %}ltr{% endif %}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Shop online{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <link rel="stylesheet" media="screen and (max-width: 988px)" href="{% static "landing/css/base_display988.css" %}">
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <style>
        .fa-stack[data-count]:after {
            position: absolute;
            right: 0%;
            top: 0%;
            content: attr(data-count);
            font-size: 40%;
            padding: .6em;
            border-radius: 999px;
            line-height: .75em;
            color: #136dc7;
            text-align: center;
            min-width: 0.5em;
            font-weight: bold;
            background: #e9f3f1;
            border-style: solid;
        }

        .color-cart {
            color: #e9f3f1;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01"
                aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse row m-4" id="navbarTogglerDemo01">
            <div class="navbar-nav me-auto ms-2 d-flex justify-content-center">
                <div class="col-2">
                    <a class="navbar-brand" href="#">{% trans 'OnlineShop' %}</a>
                </div>
                <div class="col-1 nav-item">
                    <a class="nav-link active" id="home" aria-current="page"
                       href="{% url 'landing:Home' %}">{% trans 'Home' %}</a>
                </div>
                <div class="col-1 nav-item ">
                    <a class="nav-link active"
                       href="{% url 'product:category_product' 8 %}?page=1">{% trans 'Category' %}</a>
                </div>
                <form class=" col-5 col-md-5 d-flex pe-4 display">
                    <input class="form-control me-4" type="search" placeholder="{% trans 'Search product' %}"
                           aria-label="Search">
                    <button class="btn btn-outline-light text-dark" type="submit">{% trans 'Search' %}</button>
                </form>
                <span class="fa-stack fa-1x  bg-primary display" data-count="{% if not request.COOKIES.count %} 0 {% else %}{{ request.COOKIES.count }}{% endif %}">
                        <a href="{% if request.session.uid %}{% url 'order:card_list_order' %}{% else %}{% url 'order:card_list' %}{% endif %}"><i class="fa fa-shopping-cart fa-stack-2x color-cart "></i></a>
                </span>
                <span class="ps-3 display">
                        <a href=" {% if request.session.uid %}
                            {% url 'landing:profile' %}
                        {% else %}
                            {% url 'landing:login' %}
                        {% endif %}"><i class="fa fa-user color-cart"
                                        style="font-size:28px">{{ user.first_name }}</i></a>
                </span>
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                <div class="dropdown m-1 display">
                    <p type="button" class=" dropdown-toggle text-light" data-bs-toggle="dropdown">
                        {{ CUREENT_LANG }}</p>
                    <ul class="dropdown-menu">
                        {% for lang in languages %}
                            <li>
                                <a href="/{{ lang.code }}/" {% if lang.code == LANGUAGE_CODE %}
                                   class="selected"{% endif %}>
                                    {{ lang.name_local }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</nav>
<div class="display_988" style="background-color: #286ffd ;display: none">
    <div class="container-fluid d-flex justify-content-center">
        <div class="row d-flex justify-content-center ">
            <form class="col-12 col-md-12 d-flex mt-1 d-flex justify-content-center ">
                <input class="form-control me-4 " type="search" placeholder="{% trans 'Search product' %}"
                       aria-label="Search">
                <button class="btn btn-outline-light text-dark" type="submit">{% trans 'Search' %}</button>
            </form>
        <div class="d-inline-flex ">
            <span class=" d-flex justify-content-end fa-stack fa-1x  bg-primary" data-count="5">
                        <a href="#"><i class="fa fa-shopping-cart fa-stack-2x color-cart "></i></a>
                </span>
            <span class=" d-flex justify-content-center">
                        <a href=" {% if request.session.uid %}
                            {% url 'landing:profile' %}
                        {% else %}
                            {% url 'landing:login' %}
                        {% endif %}"><i class="fa fa-user color-cart"
                                        style="font-size:28px">{{ user.first_name }}</i></a>
                </span>
            <div class="dropdown m-1   d-flex justify-content-start ">
                <p type="button" class=" dropdown-toggle text-light" data-bs-toggle="dropdown">
                    {{ CUREENT_LANG }}</p>
                <ul class="dropdown-menu">
                    {% for lang in languages %}
                        <li>
                            <a href="/{{ lang.code }}/" {% if lang.code == LANGUAGE_CODE %}
                               class="selected"{% endif %}>
                                {{ lang.name_local }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        </div>
    </div>
</div>
{% block content %}{% endblock %}
<footer class="bg-light text-center text-white">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
        <!-- Section: Social media -->
        <section class="mb-4">
            <!-- Facebook -->
            <a
                    class="btn btn-primary btn-floating m-1"
                    style="background-color: #3b5998;"
                    href="#!"
                    role="button"
            ><i class="fa fa-facebook-f"></i
            ></a>

            <!-- Twitter -->
            <a
                    class="btn btn-primary btn-floating m-1"
                    style="background-color: #55acee;"
                    href="#!"
                    role="button"
            ><i class="fa fa-twitter"></i
            ></a>

            <!-- Google -->
            <a
                    class="btn btn-primary btn-floating m-1"
                    style="background-color: #dd4b39;"
                    href="#!"
                    role="button"
            ><i class="fa fa-google"></i
            ></a>

            <!-- Instagram -->
            <a
                    class="btn btn-primary btn-floating m-1"
                    style="background-color: #ac2bac;"
                    href="#!"
                    role="button"
            ><i class="fa fa-instagram"></i
            ></a>

            <!-- Linkedin -->
            <a
                    class="btn btn-primary btn-floating m-1"
                    style="background-color: #0082ca;"
                    href="#!"
                    role="button"
            ><i class="fa fa-linkedin-square"></i
            ></a>
            <!-- Github -->
            <a
                    class="btn btn-primary btn-floating m-1"
                    style="background-color: #333333;"
                    href="#!"
                    role="button"
            ><i class="fa fa-github"></i
            ></a>
        </section>
        <!-- Section: Social media -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3 bg-primary">
        {% trans '© 2020 Copyright:' %}
        <a class="text-white" href=""> {% trans 'OnlineShop' %}</a>
    </div>
    <!-- Copyright -->
</footer>
<script>
    function home(url) {
        $.ajax({
            type: 'GET',
            url: url,
            success: function (data) {
                {#$('body').empty()#}
                $('#home').append(data)
                console.log(data)
            }
        });

    }
</script>
</body>
</html>