Project_Final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings
from landing.views import HomeView
from product.views import product_list_api, category_list_api, productListApi, productDetailApi

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('', include('landing.urls'), name='landing'),
    path('product/', include('product.urls'), name='product'),
    path('customer/', include('customer.urls'), name='customer'),
    path('order/', include('order.urls'), name='order'),
    # serializers
    # path('product/', product_list_api),
    # path('product_list/', productListApi.as_view()),
    # path('product_Detail/<int:pk>', productDetailApi.as_view()),
    # path('category/', category_list_api),
    prefix_default_language=True
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path

from customer.views import UserlistViewApi, UserDetailViewApi, AddressDetailViewApi, AddresslistViewApi, \
    AddresscreateView, AddressUpdateView, AddressDeleteView,UpdateUserView,ChangePasswordView,PasswordChangeViewDone

app_name = 'customer'
urlpatterns = [
    path('User_list/', UserlistViewApi.as_view(), name='User_list'),
    path('User_Detail_login/', UserDetailViewApi.as_view(), name='User_Detail_login'),
    path('User_update/<int:pk>', UpdateUserView.as_view(), name='User_update'),
    path('Address_list/', AddresslistViewApi.as_view(), name='Address_list'),
    path('Address_Detail/<int:pk>', AddressDetailViewApi.as_view(), name='Address_Detail'),
    path('Address_create/', AddresscreateView.as_view(), name='Address_create'),
    path('Address_update/<int:pk>', AddressUpdateView.as_view(), name='Address_update'),
    path('Address_delete/<int:pk>', AddressDeleteView.as_view(), name='Address_delete'),
    path('password_change', ChangePasswordView.as_view(), name='password_change'),
    path('password_change_done', PasswordChangeViewDone.as_view(), name='password_change_done'),
]

landing/urls.py
from django.urls import path

from .views import HomeView, LoginView, registerView, LogoutView,profileView

app_name = 'landing'
urlpatterns = [
    path('', HomeView.as_view(),name ='Home'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', registerView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', profileView.as_view(), name='profile'),
]

order/urls.py
from django.urls import path
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from order.views import OrderViewSets, Order_itemViewSets, card_list, \
    Order_items_sessionDeleteView, Order_itemsUpdate_sessionView, card_list_orderView, order_items_update_Api, \
    order_items_delete_Api, Order_delivery, Order_cancel

router = DefaultRouter()
router.register('Order', OrderViewSets, basename='Order')
router.register('Order_item', Order_itemViewSets, basename='Order_item')
app_name = 'order'
urlpatterns = [
    path('', include(router.urls)),
    path('delete_order_item/<int:pk>', order_items_delete_Api.as_view(), name='delete_order_item'),
    path('delete_order_item_session/<int:pk>', Order_items_sessionDeleteView.as_view(),
         name='delete_order_item_session'),
    path('update_order_item/<int:pk>', order_items_update_Api.as_view(), name='update_order_item'),
    path('update_order_item_session/<int:pk>', Order_itemsUpdate_sessionView.as_view(),
         name='update_order_item_session'),
    path('card_list/', card_list.as_view(), name='card_list'),
    path('card_list_order/', card_list_orderView.as_view(), name='card_list_order'),
    path('Order_delivery/<int:pk>', Order_delivery.as_view(), name='Order_delivery'),
    path('Order_cancel/<int:pk>', Order_cancel.as_view(), name='Order_cancel'),
]

customer/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
# Create your models here.
from core.models import BaseModel, User


class Address(BaseModel):
    province = models.CharField(max_length=20, null=False)
    city = models.CharField(max_length=20, null=False)
    town = models.CharField(max_length=20, null=False)
    street = models.CharField(max_length=20, null=False)
    alley = models.CharField(max_length=20, null=False)
    Plaque = models.IntegerField(unique=True, null=False)
    zip_code = models.IntegerField(unique=True, null=False)
    customer = models.ForeignKey('Customer', on_delete=models.RESTRICT,null=True,blank=True)

    def __str__(self):
        return f'{self.city}:{self.zip_code}'

    class Meta:
        verbose_name = _('Address')
        verbose_name_plural = _('Addresses')


class Customer(BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('Customer')
        verbose_name_plural = _('Customers')

    def __str__(self):
        return f'{self.user.phone}'

landing/models.py
from django.db import models

# Create your models here.

customer/forms.py
from django import forms
from customer.models import Customer
from core.models import User
from customer.models import Address
from django.contrib.auth.forms import UserCreationForm


class CustomerForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['phone', 'email', 'first_name', 'last_name']

    widgets = {
        'phone': forms.TextInput(
            attrs={'name': 'phone', 'class': 'bg-warning  justify-content-center form-control', 'id': 'phone_id'}, ),
        'email': forms.EmailInput(
            attrs={'name': 'price', 'class': 'bg-warning  justify-content-center form-control', 'id': 'email_id'}, ),
        'first_name': forms.TextInput(
            attrs={'name': 'Category', 'class': 'bg-warning  justify-content-center form-control',
                   'id': 'name_id'}, ),
        'last_name': forms.TextInput(
            attrs={'name': 'Category', 'class': 'bg-warning  justify-content-center form-control',
                   'id': 'name_id'}, )
    }


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['province', 'city', 'town', 'street', 'alley', 'Plaque', 'zip_code']

customer/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import UpdateView, DeleteView
from customer.forms import AddressForm
from customer.permissions import IsOwnerPermission, IsSuperuserPermission
from customer.serializers import AddressSerializer, CustomerSerializer
from rest_framework import generics, permissions
from customer.models import Address, Customer, User
import logging
from rest_framework import renderers
from django.contrib import messages


# Create your views here.
class UserlistViewApi(generics.ListAPIView):
    serializer_class = CustomerSerializer
    queryset = Customer.objects.all()
    permission_classes = [permissions.IsAdminUser, IsSuperuserPermission]
    # authentication_classes = [authentication.BasicAuthentication]


class UserDetailViewApi(generics.ListAPIView):
    # log userDetailView
    # logger = logging.getLogger('project.developers')
    # logger.error("see user detail view ")

    serializer_class = CustomerSerializer
    permission_classes = [permissions.IsAuthenticated]
    # authentication_classes = [authentication.BasicAuthentication]
    def get_queryset(self):
        return Customer.objects.filter(user_id=self.request.user.id)
    renderer_classes = [renderers.JSONRenderer, renderers.TemplateHTMLRenderer]
    template_name = 'landing/customer/customer_page.html'

class UpdateUserView(View):
    def post(self, request, pk):
        user_update = User.objects.get(id=pk)
        user_update.first_name = request.POST['firstname']
        user_update.last_name = request.POST['lastname']
        user_update.phone = request.POST['phone']
        user_update.email = request.POST['email']
        user_update.save()
        context = {
            'user': self.request.user
        }
        return render(request, 'landing/customer/customer_page.html', context)


class AddresslistViewApi(generics.ListAPIView):
    serializer_class = AddressSerializer
    queryset = Address.objects.all()
    permission_classes = [permissions.IsAuthenticated, IsOwnerPermission]

    # authentication_classes = [authentication.BasicAuthentication]

    def get_queryset(self):
        return Address.objects.filter(customer__user=self.request.user)

    renderer_classes = [renderers.JSONRenderer, renderers.TemplateHTMLRenderer]
    template_name = 'landing/customer/address_customer.html'


class AddressDetailViewApi(generics.RetrieveAPIView):
    serializer_class = AddressSerializer
    queryset = Address.objects.all()
    permission_classes = [permissions.IsAuthenticated, IsOwnerPermission]
    renderer_classes = [renderers.JSONRenderer, renderers.TemplateHTMLRenderer]
    template_name = 'landing/customer/detail_address.html'


# class AddresscreateViewApi(generics.CreateAPIView):
#     serializer_class = AddressSerializer
#     queryset = Address.objects.all()
#     permission_classes = [permissions.IsAuthenticated, IsOwnerPermission]

# class AddresscreateViewApi(View):
#     renderer_classes = [renderers.JSONRenderer, renderers.TemplateHTMLRenderer]
#     template_name = 'landing/customer/address_customer.html'
#
#     def get(self, request):
#         render(request, 'landing/customer/address_customer.html')
#
#     def post(self, request):
#         data = request.data
#         print('data:', data)
#         Address_serializer = AddressSerializer(data=data)
#         if Address_serializer.is_valid():
#             # new_product = Address_serializer.save()
#             print(Address_serializer.validated_data['new_product'])
#             return render(request, 'landing/customer/address_customer.html')
#         else:
#             return render(request, 'landing/customer/address_customer.html')

# class AddresscreateViewApi(CreateView):
#     model = Address
#     fields = '__all__'
#     template_name = 'landing/customer/create_Address.html'
#     success_url = reverse_lazy('customer:Address_create')

class AddresscreateView(View):
    form_class = AddressForm
    template_name = 'landing/customer/create_Address.html'

    def get(self, request):
        return render(request, 'landing/customer/create_Address.html', {'form': self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            province = request.POST["province"]
            city = request.POST["city"]
            town = request.POST["town"]
            street = request.POST["street"]
            alley = request.POST["alley"]
            plaque = request.POST["Plaque"]
            zip_code = request.POST["zip_code"]
            id_user = self.request.user.id
            customer = Customer.objects.get(user_id=id_user)
            address_new = Address.objects.create(province=province, city=city, town=town, street=street, alley=alley,
                                                 Plaque=plaque
                                                 , zip_code=zip_code, customer=customer)
            address_new.save()
            messages.add_message(request, messages.ERROR, "create success")
            return render(request, 'landing/customer/create_Address.html', {'form': self.form_class})
        messages.add_message(request, messages.ERROR, "zip code use before")
        return render(request, 'landing/customer/create_Address.html', {'form': self.form_class})


class AddressUpdateView(UpdateView):
    model = Address
    fields = ['province', 'city', 'town', 'street', 'alley', 'Plaque', 'zip_code']
    template_name = 'landing/customer/Address_update.html'
    success_url = reverse_lazy('customer:Address_list')


class AddressDeleteView(DeleteView):
    model = Address
    fields = ['province', 'city', 'town', 'street', 'alley', 'Plaque', 'zip_code']
    template_name = 'landing/customer/Address_delete.html'
    success_url = reverse_lazy('customer:Address_list')


class ChangePasswordView(LoginRequiredMixin, PasswordChangeView):
    template_name = 'landing/public/password_change_form.html'
    success_url = reverse_lazy('customer:password_change_done')


class PasswordChangeViewDone(LoginRequiredMixin, PasswordChangeDoneView):
    template_name = 'landing/public/password_change_done.html'

landing/views.py
from django.contrib.auth.models import Permission, ContentType
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render
from django.contrib import messages
# Create your views here.
from django.views.generic import TemplateView
from django.views import View

from core.models import User
from customer.forms import CustomerForm
from customer.models import Customer


class HomeView(TemplateView):
    template_name = "landing/public/Home.html"


class registerView(View):
    form_class = CustomerForm
    # template_name = 'public/register'

    def get(self, request):
        form = CustomerForm()
        return render(request, 'landing/public/register.html', {'form': form})

    def post(self, request):
        phone = request.POST['phone']
        email = request.POST['email']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        for i in User.objects.all():
            if i.phone == phone:
                messages.add_message(request, messages.ERROR, "phone is exist")
                return render(request, 'landing/public/register.html', {'form': self.form_class})
        if password2 != password1:
            messages.add_message(request, messages.ERROR, "your password not equal")
            return render(request, 'landing/public/register.html', {'form': self.form_class})
        if len(password1) < 8:
            messages.add_message(request, messages.ERROR, "your password should more than 8")
            return render(request, 'landing/public/register.html', {'form': self.form_class})
        new_user = User.objects.create_user(username=phone, email=email,
                                            first_name=first_name, last_name=last_name, password=password1, phone=phone)
        Customer.objects.create(user=new_user)
        # code add permission see-profile in terminal
        # content_type = ContentType.objects.get_for_model(User)
        # permission = Permission.objects.create(
        #     name='can see profile',
        #     codename='see_profile',
        #     content_type=content_type
        # )
        # add permission when register
        content_type = ContentType.objects.get_for_model(User)
        permission = Permission.objects.get(content_type=content_type, codename='see_profile')
        new_user.user_permissions.add(permission)
        return render(request, 'landing/public/Login.html')


class LoginView(View):
    def get(self, request):
        # if request.session.get('uid', None) is None:
        return render(request, 'landing/public/Login.html')

    def post(self, request):
        phone = request.POST['phone']
        password = request.POST['password']

        user = User.objects.get(phone=phone)
        if not user.check_password(password):
            messages.add_message(request, messages.ERROR, "your password wrong")
            return render(request, 'landing/public/Login.html')
        request.session['uid'] = user.id
        from product.Cart import Cart
        from order.order_item_add import Order_User
        cart = Cart(request)
        user = Order_User(user)
        user.add_session(cart)
        len_order_user = user.get_user()
        cart.clear()  # remove session cart
        # set cookie
        user = {
            'user': user,
        }
        response = render(request, 'landing/public/Home.html', context=user)
        response.set_cookie('count', len_order_user[3])

        return response


class LogoutView(View):

    def get(self, request):
        if request.session.get('uid', None) is None:
            return render(request, 'landing/public/Home.html')
        del request.session['uid']
        response = render(request, 'landing/public/Home.html')
        response.delete_cookie('count')
        return response


class profileView(View):
    # permission_required = "landing.see_profile"

    def get(self, request):
        user = User.objects.get(id=request.session.get('uid', None))
        user = {
            'user': user

        }

        return render(request, 'landing/public/profile.html', context=user)

templates/landing/customer/Address_delete.html
{% extends "landing/public/profile.html" %}
{% load i18n %}
{% block title %} Address delet {% endblock %}
{% block profile %}
        <div class="container mt-10 justify-content-center">
        <h1 class="mr-30"> delete address</h1>
        <form action="" method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete with zip_code "{{ object.zip_code }}"?</p>
            <input type="submit" value="Confirm">
        </form>
    </div>

{% endblock %}

templates/landing/customer/Address_update.html
{% extends "landing/public/profile.html" %}
{% load i18n %}
{% block title %} Address update {% endblock %}
{% block profile %}
        <div class="container mt-10 justify-content-center">
        <h1 class="mr-30"> update address</h1>
        <form action="" method="post">
            {% csrf_token %}
            <div class="row mt-3 justify-content-center">
                <table class="table table-striped">
                    {{ form.as_table }}
                </table>
                <input class="bg-primary w-25 h-50 mt-5 mb-2" type="submit" value="update">
            </div>
        </form>
    </div>
{% endblock %}

templates/landing/customer/address_customer.html
{% extends "landing/public/profile.html" %}
{% load i18n %}
{% block title %} Address List {% endblock %}
{% block profile %}
    <div class="list-group me-2">
        <a href="#" class="list-group-item bg-danger border-danger list-group-item-action active" aria-current="true">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{% trans 'List Address' %}</h5>
            </div>
            <p class="mb-1">{% trans 'please Check the address information before ordering ' %}</p>
        </a>
        {% for address in  results %}
            <a href="{% url 'customer:Address_Detail' address.id %}" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <div>
                        <h5 class="mb-1">{% trans 'province' %}:</h5>
                        <h5 class="mb-1">{{ address.province }}</h5>
                    </div>
                    <div>
                        <h5 class="mb-1">{% trans 'city' %}:</h5>
                        <h5 class="mb-1">{{ address.city }}</h5>
                    </div>
                    <div>
                        <h5 class="mb-1">{% trans 'town' %}:</h5>
                        <h5 class="mb-1">{{ address.town }}</h5>
                    </div>
                    <div>
                        <h5 class="mb-1">{% trans 'street' %}:</h5>
                        <h5 class="mb-1">{{ address.street }}</h5>
                    </div>
                </div>
                <p class="mb-1">{% trans 'alley' %}:{{ address.alley }}</p>
                <small class="text-muted">{% trans 'codeـhome' %}: {{ address.zip_code }}</small>
            </a>
        {% endfor %}
        <a href="{% url 'customer:Address_create' %}" class="justify-content-center"><input class="btn btn-danger text-light justify-content-center mt-3"
               type="submit" value=" {% trans 'create new Address' %}"></a>
    </div>
{% endblock %}

templates/landing/customer/create_Address.html
{% extends "landing/public/profile.html" %}
{% block title %} create_customer {% endblock %}
{% block profile %}
<div class="container mt-10 justify-content-center">
    <h1 class="mr-30"> CREATE Address</h1>
        {% if messages %}
            {% for msg in messages %}
                {% if msg.level != DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    <div class="alert alert-warning mt-4 {{ msg.tags }}" role="alert">
                        <strong>{{ msg }}</strong>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    <form action="{% url 'customer:Address_create' %}"  method="post">
        {% csrf_token %}
        <div class="row mt-3 justify-content-center">

            <table class="table table-striped">
                {{ form.as_table }}
            </table>
            <input class="bg-primary  h-50 mt-5 mb-2" type="submit" value="create Address">
        </div>
    </form>
</div>
{% endblock %}

templates/landing/customer/customer_page.html
{% extends "landing/public/profile.html" %}
{% load i18n %}
{% block title %} Login {% endblock %}
{% block profile %}
    {% csrf_token %}
    <div class="container rounded bg-white mb-5 ">
        <div class="row d-flex justify-content-center">
            <div class="col-md-10 border-right ">
                <div class="p-3">
                    <div class="d-flex justify-content-center align-items-center mb-3">
                        <h4 class="text-right">{% trans 'Profile' %} </h4>
                    </div>
                    <form action="{% url 'customer:User_update' user.id %}" method="post">
                        {% csrf_token %}
                        <div class="row mt-2 ">
                            <div class="col-md-6"><label class="labels">{% trans 'Name' %}</label><input type="text"
                                                                                                         class="form-control"
                                                                                                         name="firstname"
                                                                                                         placeholder="first name"
                                                                                                         value="{{ user.first_name }}">
                            </div>
                            <div class="col-md-6"><label class="labels">{% trans 'Surname' %}</label><input type="text"
                                                                                                            class="form-control"
                                                                                                            name="lastname"
                                                                                                            value="{{ user.last_name }}"
                                                                                                            placeholder="surname">
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-md-12"><label class="labels">{% trans 'Mobile Number' %}</label><input
                                    type="text"
                                    class="form-control"
                                    name="phone"
                                    placeholder="enter phone number"
                                    value="{{ user.phone }}"></div>
                            <div class="col-md-12"><label class="labels">{% trans 'Email ID' %}</label><input
                                    type="text"
                                    class="form-control"
                                    name="email"
                                    placeholder="enter email id"
                                    value="{{ user.email }}"></div>
                            {#                        <div class="col-md-12"><label class="labels">{% trans 'last login' %}</label>#}
                            {#                            <p type="text" class="form-control">{{ user.last_login}} {% now "SHORT_DATETIME_FORMAT" %}</p></div>#}
                        </div>

                       <div class="mt-5 text-center">
                                                    <input type="submit" class="btn btn-primary profile-button" value="{% trans 'Save Profile' %}">
                        </div>
                    </form>
                    <div class="mt-5 text-center">
                        <a href="{% url 'customer:password_change' %}">
                            <button class="btn btn-primary profile-button"
                                    type="button">{% trans 'Change password user name' %}</button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/landing/customer/detail_address.html
{% extends "landing/public/profile.html" %}
{% load i18n %}
{% block title %} Address Detail {% endblock %}
{% block profile %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">{% trans 'province' %}</th>
            <th scope="col">{% trans 'town' %}</th>
            <th scope="col">{% trans 'city' %}</th>
            <th scope="col">{% trans 'street' %}</th>
            <th scope="col">{% trans 'alley' %}</th>
            <th scope="col">{% trans 'Plaque' %}</th>
            <th scope="col">{% trans 'zip_code' %}</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ province }}</td>
            <td>{{ town }}</td>
            <td>{{ city }}</td>
            <td>{{ street }}</td>
            <td>{{ alley }}</td>
            <td>{{ Plaque }}</td>
            <td>{{ zip_code }}</td>
            <td><a href="{% url 'customer:Address_update' id %}" class="">
            <i class="fa fa-pencil-square " style="font-size:20px"></i>
            </a></td>
            <td><a href="{% url 'customer:Address_delete' id %}" class="">
            <i class="fa fa-trash " style="font-size:20px"></i>
        </a></td>
        </tr>
        </tbody>
    </table>
{% endblock %}