Project_Final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings
from landing.views import HomeView
from product.views import product_list_api, category_list_api, productListApi, productDetailApi

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('', include('landing.urls'), name='landing'),
    path('product/', include('product.urls'), name='product'),
    path('customer/', include('customer.urls'), name='customer'),
    path('order/', include('order.urls'), name='order'),
    # serializers
    # path('product/', product_list_api),
    # path('product_list/', productListApi.as_view()),
    # path('product_Detail/<int:pk>', productDetailApi.as_view()),
    # path('category/', category_list_api),
    prefix_default_language=True
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/urls.py
from django.urls import path

from .views import HomeView, LoginView, registerView, LogoutView,profileView

app_name = 'landing'
urlpatterns = [
    path('', HomeView.as_view(),name ='Home'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', registerView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', profileView.as_view(), name='profile'),
]

order/urls.py
from django.urls import path
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from order.views import OrderViewSets, Order_itemViewSets, card_list, \
    Order_items_sessionDeleteView, Order_itemsUpdate_sessionView, card_list_orderView, order_items_update_Api, \
    order_items_delete_Api, Order_delivery, Order_cancel

router = DefaultRouter()
router.register('Order', OrderViewSets, basename='Order')
router.register('Order_item', Order_itemViewSets, basename='Order_item')
app_name = 'order'
urlpatterns = [
    path('', include(router.urls)),
    path('delete_order_item/<int:pk>', order_items_delete_Api.as_view(), name='delete_order_item'),
    path('delete_order_item_session/<int:pk>', Order_items_sessionDeleteView.as_view(),
         name='delete_order_item_session'),
    path('update_order_item/<int:pk>', order_items_update_Api.as_view(), name='update_order_item'),
    path('update_order_item_session/<int:pk>', Order_itemsUpdate_sessionView.as_view(),
         name='update_order_item_session'),
    path('card_list/', card_list.as_view(), name='card_list'),
    path('card_list_order/', card_list_orderView.as_view(), name='card_list_order'),
    path('Order_delivery/<int:pk>', Order_delivery.as_view(), name='Order_delivery'),
    path('Order_cancel/<int:pk>', Order_cancel.as_view(), name='Order_cancel'),
]

landing/models.py
from django.db import models

# Create your models here.

order/models.py
import datetime

from django.db import models
from core.models import BaseModel, BaseDiscount
from product.models import Product
from customer.models import Address

from model_utils import Choices

from django.utils import timezone

from django.utils.translation import gettext_lazy as _


# Create your models here.


class Of_code(BaseDiscount):
    off_code = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return f'{self.type}:{self.value}'

    class Meta:
        verbose_name = _('Off_code')
        verbose_name_plural = _('Off_codes')


class Order_item(BaseModel):
    Product = models.ForeignKey(Product, on_delete=models.RESTRICT, null=False)
    Count = models.PositiveIntegerField(null=True, blank=True, default=1)

    def __str__(self):
        return f'{self.Product}:{self.Count}'

    @property
    def get_cost_end_product(self):
        return ((self.Product.price - self.Product.category.discount.profit_value(self.Product.price)) -
                self.Product.discount.profit_value(self.Product.price)) * self.Count

    class Meta:
        verbose_name = _('Order item')
        verbose_name_plural = _('Order items')


ORDER_STATUS = Choices(
    (1, 'Current', 'Current'),
    (2, 'Delivered', 'Delivered'),
    (3, 'Canceled', 'Canceled')
)


class Order(BaseModel):
    address = models.ForeignKey(Address, on_delete=models.RESTRICT, null=False)
    order_items = models.ManyToManyField(Order_item)
    status_Order = models.IntegerField(choices=ORDER_STATUS, default=1, null=True, blank=True)
    date = models.DateTimeField(default=timezone.now)
    off_code = models.ForeignKey(Of_code, on_delete=models.RESTRICT)

    @property
    def get_total_cost(self):
        return sum(item.get_cost_end_product for item in self.order_items.all())

    @property
    def get_all_order_items(self):
        return [item.Product.name_product for item in self.order_items.all()]

    def __str__(self):
        return f'{self.address}:{self.date.year}'

    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Order')

landing/views.py
from django.contrib.auth.models import Permission, ContentType
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render
from django.contrib import messages
# Create your views here.
from django.views.generic import TemplateView
from django.views import View

from core.models import User
from customer.forms import CustomerForm
from customer.models import Customer


class HomeView(TemplateView):
    template_name = "landing/public/Home.html"


class registerView(View):
    form_class = CustomerForm
    # template_name = 'public/register'

    def get(self, request):
        form = CustomerForm()
        return render(request, 'landing/public/register.html', {'form': form})

    def post(self, request):
        phone = request.POST['phone']
        email = request.POST['email']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        for i in User.objects.all():
            if i.phone == phone:
                messages.add_message(request, messages.ERROR, "phone is exist")
                return render(request, 'landing/public/register.html', {'form': self.form_class})
        if password2 != password1:
            messages.add_message(request, messages.ERROR, "your password not equal")
            return render(request, 'landing/public/register.html', {'form': self.form_class})
        if len(password1) < 8:
            messages.add_message(request, messages.ERROR, "your password should more than 8")
            return render(request, 'landing/public/register.html', {'form': self.form_class})
        new_user = User.objects.create_user(username=phone, email=email,
                                            first_name=first_name, last_name=last_name, password=password1, phone=phone)
        Customer.objects.create(user=new_user)
        # code add permission see-profile in terminal
        # content_type = ContentType.objects.get_for_model(User)
        # permission = Permission.objects.create(
        #     name='can see profile',
        #     codename='see_profile',
        #     content_type=content_type
        # )
        # add permission when register
        content_type = ContentType.objects.get_for_model(User)
        permission = Permission.objects.get(content_type=content_type, codename='see_profile')
        new_user.user_permissions.add(permission)
        return render(request, 'landing/public/Login.html')


class LoginView(View):
    def get(self, request):
        # if request.session.get('uid', None) is None:
        return render(request, 'landing/public/Login.html')

    def post(self, request):
        phone = request.POST['phone']
        password = request.POST['password']

        user = User.objects.get(phone=phone)
        if not user.check_password(password):
            messages.add_message(request, messages.ERROR, "your password wrong")
            return render(request, 'landing/public/Login.html')
        request.session['uid'] = user.id
        from product.Cart import Cart
        from order.order_item_add import Order_User
        cart = Cart(request)
        user = Order_User(user)
        user.add_session(cart)
        len_order_user = user.get_user()
        cart.clear()  # remove session cart
        # set cookie
        user = {
            'user': user,
        }
        response = render(request, 'landing/public/Home.html', context=user)
        response.set_cookie('count', len_order_user[3])

        return response


class LogoutView(View):

    def get(self, request):
        if request.session.get('uid', None) is None:
            return render(request, 'landing/public/Home.html')
        del request.session['uid']
        response = render(request, 'landing/public/Home.html')
        response.delete_cookie('count')
        return response


class profileView(View):
    # permission_required = "landing.see_profile"

    def get(self, request):
        user = User.objects.get(id=request.session.get('uid', None))
        user = {
            'user': user

        }

        return render(request, 'landing/public/profile.html', context=user)

order/views.py
from django.shortcuts import render
from django.views import View
from rest_framework import viewsets, renderers
from rest_framework import permissions, generics
from django.utils import timezone

# Create your views here.
from order.models import Order, Order_item
from order.serializers import OrderSerializer, Order_itemSerializer

from customer.permissions import IsOwnerPermission, IsSuperuserPermission


class OrderViewSets(viewsets.ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer

    # permission_classes = [IsOwnerPermission, permissions.IsAuthenticated]

    def get_queryset(self):
        return Order.objects.filter(address__customer__user=self.request.user)

    renderer_classes = [renderers.JSONRenderer, renderers.TemplateHTMLRenderer]
    template_name = 'landing/order/order_customer.html'


class Order_itemViewSets(viewsets.ModelViewSet):
    queryset = Order_item.objects.all()
    serializer_class = Order_itemSerializer


class Order_items_sessionDeleteView(View):
    def post(self, request, pk):
        from product.Cart import Cart
        cart = Cart(request)
        cart.remove(pk)
        response = render(request, 'landing/order/cart_list.html')
        response.set_cookie('count', len(cart))
        return response


class Order_itemsUpdate_sessionView(View):
    def post(self, request, pk):
        from product.Cart import Cart
        cart = Cart(request)
        cart.update(pk, int(request.POST['number']))
        response = render(request, 'landing/order/cart_list.html')
        response.set_cookie('count', len(cart))
        return response


class card_list(View):
    def get(self, request):
        from product.Cart import Cart
        cart = Cart(request)
        context = {
            'data_cart': cart.data_cart(),
            'data_product': cart.data_product(),
            'get_total_price': cart.get_total_price(),
            'len_cart': len(cart),

        }
        return render(request, 'landing/order/cart_list.html', context=context)

    # def get(self, request):
    #     from core.models import User
    #     user = User.objects.get(id=request.session.get('uid'))
    #     from order.order_item_add import Order_User
    #     user = Order_User(user)
    #     print(user.get_user())
    #     order_id = user.get_user()[2]
    #     order_list = Order.objects.get(id=order_id)
    #     context = {
    #         'context': order_list
    #     }
    #     return render(request, 'landing/order/cart_list_order_customer.html', context=context)


class card_list_orderView(generics.ListAPIView):
    serializer_class = OrderSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        return Order.objects.filter(address__customer__user_id=self.request.user.id, status_Order=1)

    renderer_classes = [renderers.JSONRenderer, renderers.TemplateHTMLRenderer]
    template_name = 'landing/order/cart_list_order_customer.html'


class order_items_update_Api(View):
    def post(self, request, pk):
        order_item_update = Order_item.objects.get(id=pk)
        order_item_update.Count = int(request.POST['number'])
        order_item_update.save()
        return render(request, 'landing/order/cart_list_order_customer.html')


class order_items_delete_Api(View):
    def post(self, request, pk):
        order_item_delete = Order_item.objects.get(id=pk)
        order_item_delete.delete()
        return render(request, 'landing/order/cart_list_order_customer.html')




class Order_delivery(View):
    def post(self, request, pk):
        now = timezone.now
        order_delivery = Order.objects.get(id=pk)
        print(order_delivery.status_Order)
        order_delivery.status_Order = 2
        # create_new_order = Order.objects.create(created=now, last_updated=now, is_deleted=0, is_active=1,
        #                                         status_Order=1, date=now,
        #                                         address=order_delivery.address.id,
        #                                         off_code=1)
        # create_new_order.save()
        order_delivery.save()
        return render(request, 'landing/order/cart_list_order_customer.html')


class Order_cancel(View):
    def post(self, request, pk):
        order_delivery = Order.objects.get(id=pk)
        order_delivery.status_Order = 3
        order_delivery.save()
        return render(request, 'landing/order/cart_list_order_customer.html')

templates/landing/order/cart_list_order_customer.html
{% extends "landing/base/_base.html" %}
{% load static %}
{% load i18n %}
{% block title %} cart list {% endblock %}
{% block content %}
    {% csrf_token %}
    <section class="h-100 gradient-custom">
        <div class="container py-5">
            <div class="row d-flex justify-content-center my-4">
                <div class="col-md-8">
                    <div class="card mb-4">
                        <div class="card-header py-3">
                            <h5 class="mb-0">{% trans 'Cartitems' %}</h5>
                        </div>
                        <div class="card-body ">
                            <!-- Single item -->
                            <div class="row">
                                {% for res in results %}
                                    {% for order_item in res.order_items %}
                                        <div class="col-lg-3 col-md-12 mb-4 mb-lg-0 {{ order_item.id }} {{ res.id }}">
                                            <!-- Image -->
                                            <div class="bg-image hover-overlay hover-zoom ripple rounded"
                                                 data-mdb-ripple-color="light">
                                                <img src="{{ order_item.Product.image }}"
                                                     class="w-100" alt="dont exist picture"/>
                                                <a href="">
                                                    <div class="mask"
                                                         style="background-color: rgba(251, 251, 251, 0.2)"></div>
                                                </a>
                                            </div>
                                            <!-- Image -->
                                        </div>
                                        <div class="col-lg-5 col-md-6 mb-4 mb-lg-0 {{ order_item.id }} {{ res.id }}">
                                            <!-- Data -->
                                            <p><strong>{{ order_item.Product.name_product }}</strong></p>
                                            <p>{% trans 'brand' %} : {{ order_item.Product.brand }}</p>
                                            <button type="button" class="btn btn-primary btn-sm me-1 mb-2"
                                                    data-mdb-toggle="tooltip"
                                                    title="Remove item"
                                                    onclick="remove_item('{% url 'order:delete_order_item' order_item.id %}',{{ order_item.id }})">
                                                <i class="fa fa-trash"></i>
                                            </button>
                                            <button type="button" class="btn btn-danger btn-sm mb-2"
                                                    data-mdb-toggle="tooltip"
                                                    title="Move to the wish list">
                                                <i class="fa fa-heart"></i>
                                            </button>
                                            <!-- Data -->
                                        </div>

                                        <div class="col-lg-4 col-md-6 mb-4 mb-lg-0 {{ order_item.id }} {{ res.id }}">
                                            <!-- Quantity -->
                                            <div class="d-flex mb-4" style="max-width: 300px">
                                                <button class="btn btn-primary px-3 me-2"
                                                        onclick="this.parentNode.querySelector('input[type=number]').stepDown();
                                                                update_item('{% url 'order:update_order_item' order_item.id %}',{{ order_item.id }});">
                                                    <i class="fa fa-minus"></i>
                                                </button>

                                                <div class="form-outline">
                                                    <input id="{{ order_item.id }}" min="1"
                                                           name="{{ order_item.Product.number_store }}"
                                                           max="{{ order_item.Product.number_store }}"
                                                           value="{{ order_item.Count }}"
                                                           type="number"
                                                           class="form-control"/>
                                                </div>

                                                <button class="btn btn-primary px-3 ms-2"
                                                        onclick="this.parentNode.querySelector('input[type=number]').stepUp();
                                                                update_item('{% url 'order:update_order_item' order_item.id %}',{{ order_item.id }});">
                                                    <i class="fa fa-plus"></i>
                                                </button>
                                            </div>
                                            <!-- Quantity -->

                                            <!-- Price -->
                                            <p class="text-start text-md-center">
                                                <strong>{% trans 'one product' %}:{{ order_item.Product.price }} {% trans 'Rial' %}</strong>
                                            </p>
                                            <p class="text-start text-md-center">
                                                <strong>{% trans 'total_price' %}:{{ order_item.total_price }} {% trans 'Rial' %}</strong>
                                            </p>
                                            <!-- Price -->
                                        </div>

                                    {% endfor %}

                                    </div>
                                    </div>
                                    </div>
                                    <div class="card mb-4">
                                        <div class="card-body">
                                            <p><strong>{% trans 'Expected shipping delivery' %}</strong></p>
                                            <p class="mb-0">12.10.2020 - 14.10.2020</p>
                                        </div>
                                    </div>
                                    <div class="card mb-4 mb-lg-0">
                                        <div class="card-body">
                                            <p><strong>{% trans 'We accept' %}</strong></p>
                                            <img class="me-2" width="45px"
                                                 src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/visa.svg"
                                                 alt="Visa"/>
                                            <img class="me-2" width="45px"
                                                 src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/amex.svg"
                                                 alt="American Express"/>
                                            <img class="me-2" width="45px"
                                                 src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/mastercard.svg"
                                                 alt="Mastercard"/>

                                        </div>
                                    </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="card mb-4">
                                            <div class="card-header py-3">
                                                <h5 class="mb-0">{% trans 'Summary' %}</h5>
                                            </div>
                                            <div class="card-body">
                                                <ul class="list-group list-group-flush">
                                                    <li
                                                            class="list-group-item d-flex justify-content-between align-items-center border-0
                                    px-0 pb-0">
                                                        {% trans 'Products price' %}:
                                                        <span>{{ get_total_price }} {% trans 'Rial' %}</span>
                                                    </li>
                                                    <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                                                        {% trans 'Off_code' %}
                                                        <input class="text">
                                                    </li>
                                                    <li
                                                            class="list-group-item d-flex justify-content-between align-items-center border-0
                                    px-0 mb-3">
                                                        <div>
                                                            <strong>{% trans 'Total amount' %}</strong>
                                                        </div>
                                                        <span><strong>{{ get_total_price }} {% trans 'Rial' %}</strong></span>
                                                    </li>
                                                </ul>
                                                <button type="button"
                                                        onclick=" order_cancel('{% url 'order:Order_cancel' res.id %}',{{ res.id }});"
                                                        class="btn btn-danger btn-lg btn-block">{% trans 'canceled' %}</button>

                                                <button type="button"
                                                        onclick=" order_delivery('{% url 'order:Order_delivery' res.id %}',{{ res.id }});"
                                                        class="btn btn-success btn-lg
                                                        btn-block">{% trans 'Delivered' %}</button>
                                            </div>
                                        </div>
                                    </div>
                                    </div>
                                    </div>
                                {% endfor %}

    </section>
    <script>
        function remove_item(url, id) {
            csrfmiddlewaretoken = $('input[name=csrfmiddlewaretoken]').val()
            $(`.${id}`).remove()
            var sendInfo = {
                csrfmiddlewaretoken: csrfmiddlewaretoken,
                id: id,
            };
            $.ajax({
                type: "POST",
                url: url,
                dataType: "json",
                headers: {
                    "X-CSRFToken": csrfmiddlewaretoken
                },
                success: () => {
                },
                data: sendInfo
            });

        }

        function update_item(url, id) {
            var number = $(`#${id}`).val();
            console.log(number)
            csrfmiddlewaretoken = $('input[name=csrfmiddlewaretoken]').val()
            console.log(csrfmiddlewaretoken)
            var sendInfo = {
                csrfmiddlewaretoken: csrfmiddlewaretoken,
                id: id,
                number: parseInt(number)
            };
            $.ajax({
                type: "POST",
                url: url,
                headers: {
                    "X-CSRFToken": csrfmiddlewaretoken
                },
                success: () => {
                },
                data: sendInfo,
                error: function () {
                    console.log(error)
                }
            });
        }

        function order_delivery(url, id) {
            $(`.${id}`).remove()
            console.log(id)
            csrfmiddlewaretoken = $('input[name=csrfmiddlewaretoken]').val()
            var sendInfo = {
                csrfmiddlewaretoken: csrfmiddlewaretoken,
            };
            $.ajax({
                type: "POST",
                url: url,
                headers: {
                    "X-CSRFToken": csrfmiddlewaretoken
                },
                success: () => {
                },
                data: sendInfo,
            });
        }

        function order_cancel(url,id) {
            $(`.${id}`).remove()
            csrfmiddlewaretoken = $('input[name=csrfmiddlewaretoken]').val()
            var sendInfo = {
                csrfmiddlewaretoken: csrfmiddlewaretoken,
            };
            $.ajax({
                type: "POST",
                url: url,
                headers: {
                    "X-CSRFToken": csrfmiddlewaretoken
                },
                success: () => {
                },
                data: sendInfo,
            });
        }
    </script>
{% endblock %}