Project_Final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings
from landing.views import HomeView
from product.views import product_list_api, category_list_api, productListApi, productDetailApi

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('', include('landing.urls'), name='landing'),
    path('product/', include('product.urls'), name='product'),
    path('customer/', include('customer.urls'), name='customer'),
    path('order/', include('order.urls'), name='order'),
    # serializers
    # path('product/', product_list_api),
    # path('product_list/', productListApi.as_view()),
    # path('product_Detail/<int:pk>', productDetailApi.as_view()),
    # path('category/', category_list_api),
    prefix_default_language=True
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/urls.py
from django.urls import path

from .views import HomeView, LoginView, registerView, LogoutView,profileView

app_name = 'landing'
urlpatterns = [
    path('', HomeView.as_view(),name ='Home'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', registerView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', profileView.as_view(), name='profile'),
]

order/urls.py
from django.urls import path
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from order.views import OrderViewSets, Order_itemViewSets, card_list, \
    Order_items_sessionDeleteView, Order_itemsUpdate_sessionView, card_list_orderView, order_items_update_Api, \
    order_items_delete_Api, Order_delivery, Order_cancel

router = DefaultRouter()
router.register('Order', OrderViewSets, basename='Order')
router.register('Order_item', Order_itemViewSets, basename='Order_item')
app_name = 'order'
urlpatterns = [
    path('', include(router.urls)),
    path('delete_order_item/<int:pk>', order_items_delete_Api.as_view(), name='delete_order_item'),
    path('delete_order_item_session/<int:pk>', Order_items_sessionDeleteView.as_view(),
         name='delete_order_item_session'),
    path('update_order_item/<int:pk>', order_items_update_Api.as_view(), name='update_order_item'),
    path('update_order_item_session/<int:pk>', Order_itemsUpdate_sessionView.as_view(),
         name='update_order_item_session'),
    path('card_list/', card_list.as_view(), name='card_list'),
    path('card_list_order/', card_list_orderView.as_view(), name='card_list_order'),
    path('Order_delivery/<int:pk>', Order_delivery.as_view(), name='Order_delivery'),
    path('Order_cancel/<int:pk>', Order_cancel.as_view(), name='Order_cancel'),
]

product/urls.py
from django.urls import path

from .views import product_for_categoryListview, ProductDetailView,add_to_OrderView

app_name = 'product'
urlpatterns = [
    # path('Category/', CategoryListview.as_view(), name='category'),
    # path('product/', productListview.as_view(), name='product'),
    path('category_product/<int:pk>', product_for_categoryListview.as_view(), name='category_product'),
    path('Detail_product/<int:pk>', ProductDetailView.as_view(), name='Detail_product'),
    path('add_product/<int:pk>', add_to_OrderView.as_view(), name='add_product'),
]

landing/models.py
from django.db import models

# Create your models here.

product/models.py
from django.db import models
from core.models import BaseModel, BaseDiscount
from django.utils.translation import gettext_lazy as _


# Create your models here.
class Discount(BaseDiscount):
    pass

    def __str__(self):
        return f'{self.type}:{self.value}'

    class Meta:
        verbose_name = _('Discount')
        verbose_name_plural = _('Discounts')


class Category(BaseModel):
    category_name = models.CharField(max_length=20, null=True, blank=True)
    category_root = models.ForeignKey('self', on_delete=models.CASCADE, related_name='sub_categories',
                                      verbose_name='Parent Category',
                                      null=True, blank=True)
    discount = models.ForeignKey(Discount, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f'{self.category_name}'

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Category')


class Product(BaseModel):
    name_product = models.CharField(max_length=20, null=False)
    brand = models.CharField(max_length=20, null=True, blank=True)
    descriptions = models.TextField(max_length=250, null=True, blank=True)
    price = models.PositiveIntegerField(null=False)
    number_store = models.PositiveIntegerField(default=1)
    status = models.CharField(max_length=15, choices=(('exist', True), ('Not exist', False)), default=False)
    category = models.ForeignKey(Category, on_delete=models.RESTRICT, null=False)
    image = models.FileField(default='NO_pic.png', upload_to='Product_pic/%Y/%m/%d')
    discount = models.ForeignKey(Discount, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name_product}'

    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

landing/views.py
from django.contrib.auth.models import Permission, ContentType
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render
from django.contrib import messages
# Create your views here.
from django.views.generic import TemplateView
from django.views import View

from core.models import User
from customer.forms import CustomerForm
from customer.models import Customer


class HomeView(TemplateView):
    template_name = "landing/public/Home.html"


class registerView(View):
    form_class = CustomerForm
    # template_name = 'public/register'

    def get(self, request):
        form = CustomerForm()
        return render(request, 'landing/public/register.html', {'form': form})

    def post(self, request):
        phone = request.POST['phone']
        email = request.POST['email']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        for i in User.objects.all():
            if i.phone == phone:
                messages.add_message(request, messages.ERROR, "phone is exist")
                return render(request, 'landing/public/register.html', {'form': self.form_class})
        if password2 != password1:
            messages.add_message(request, messages.ERROR, "your password not equal")
            return render(request, 'landing/public/register.html', {'form': self.form_class})
        if len(password1) < 8:
            messages.add_message(request, messages.ERROR, "your password should more than 8")
            return render(request, 'landing/public/register.html', {'form': self.form_class})
        new_user = User.objects.create_user(username=phone, email=email,
                                            first_name=first_name, last_name=last_name, password=password1, phone=phone)
        Customer.objects.create(user=new_user)
        # code add permission see-profile in terminal
        # content_type = ContentType.objects.get_for_model(User)
        # permission = Permission.objects.create(
        #     name='can see profile',
        #     codename='see_profile',
        #     content_type=content_type
        # )
        # add permission when register
        content_type = ContentType.objects.get_for_model(User)
        permission = Permission.objects.get(content_type=content_type, codename='see_profile')
        new_user.user_permissions.add(permission)
        return render(request, 'landing/public/Login.html')


class LoginView(View):
    def get(self, request):
        # if request.session.get('uid', None) is None:
        return render(request, 'landing/public/Login.html')

    def post(self, request):
        phone = request.POST['phone']
        password = request.POST['password']

        user = User.objects.get(phone=phone)
        if not user.check_password(password):
            messages.add_message(request, messages.ERROR, "your password wrong")
            return render(request, 'landing/public/Login.html')
        request.session['uid'] = user.id
        from product.Cart import Cart
        from order.order_item_add import Order_User
        cart = Cart(request)
        user = Order_User(user)
        user.add_session(cart)
        len_order_user = user.get_user()
        cart.clear()  # remove session cart
        # set cookie
        user = {
            'user': user,
        }
        response = render(request, 'landing/public/Home.html', context=user)
        response.set_cookie('count', len_order_user[3])

        return response


class LogoutView(View):

    def get(self, request):
        if request.session.get('uid', None) is None:
            return render(request, 'landing/public/Home.html')
        del request.session['uid']
        response = render(request, 'landing/public/Home.html')
        response.delete_cookie('count')
        return response


class profileView(View):
    # permission_required = "landing.see_profile"

    def get(self, request):
        user = User.objects.get(id=request.session.get('uid', None))
        user = {
            'user': user

        }

        return render(request, 'landing/public/profile.html', context=user)

product/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, reverse
from django.http import Http404, JsonResponse, HttpResponse
# Create your views here.
from django.views.decorators.csrf import csrf_exempt
from rest_framework.decorators import api_view
from django.views import View
from django.views.generic import ListView, DetailView

from order.models import Order_item
from product.serializers import ProductSerializer, CategorySerializer
from product.models import Product, Category
from rest_framework.response import Response
from rest_framework import generics


# @csrf_exempt
# def product_list_api(request):
#     if request.method == 'GET':
#         product_serializer = ProductSerializer(Product.objects.all(), many=True)
#         return JsonResponse({'data': product_serializer.data}, status=200)
#     elif request.method == 'POST':
#         data = request.POST
#         print('data:', data)
#         product_serializer = ProductSerializer(data=data)
#         if product_serializer.is_valid():
#             new_product = product_serializer.save()
#             # print(product_serializer.validated_data['new_product'])
#             return JsonResponse({'new_product_id': new_product.id}, status=201)
#         else:
#             return JsonResponse({'errors': product_serializer.errors}, status=400)
#     else:
#         return JsonResponse({}, status=405)


@api_view(['GET', 'POST'])
def product_list_api(request):
    if request.method == 'GET':
        product_serializer = ProductSerializer(Product.objects.all(), many=True)
        return Response({'data': product_serializer.data}, status=200)
    elif request.method == 'POST':
        data = request.data
        print('data:', data)
        product_serializer = ProductSerializer(data=data)
        if product_serializer.is_valid():
            new_product = product_serializer.save()
            # print(product_serializer.validated_data['new_product'])
            return Response({'new_product_id': new_product.id}, status=201)
        else:
            return Response({'errors': product_serializer.errors}, status=400)
    else:
        return Response({}, status=405)


@api_view(['GET', 'POST'])
def category_list_api(request):
    if request.method == 'GET':
        category_serializer = CategorySerializer(Category.objects.all(), many=True)
        return Response({'data': category_serializer.data}, status=200)
    elif request.method == 'POST':
        data = request.POST
        print('data:', data)
        category_serializer = CategorySerializer(data=data)
        if category_serializer.is_valid():
            new_category = category_serializer.save()
            # print(product_serializer.validated_data['new_product'])
            return Response({'new_product_id': new_category.id}, status=201)
        else:
            return Response({'errors': category_serializer.errors}, status=400)
    else:
        return Response({}, status=405)


class productListApi(generics.ListAPIView, generics.CreateAPIView):
    serializer_class = ProductSerializer
    queryset = Product.objects.all()


class productDetailApi(generics.RetrieveUpdateDestroyAPIView):
    serializer_class = ProductSerializer
    queryset = Product.objects.all()


# class CategoryListview(View):
#
#     def get(self, request):
#         category_list = Category.objects.all()
#         context = {
#             'Category_list': category_list,
#         }
#         return render(request, 'landing/product/Category.html', context=context)


# class CategoryListview(View):
#     model = Category
#     template_name = 'landing/product/Category.html'
#     context_object_name = 'Category_list'


# class productListview(ListView):
#     model = Product
#     template_name = 'landing/product/List_product.html'
#     context_object_name = 'product_list'


class product_for_categoryListview(View):

    def get(self, request, pk):
        category_list = Category.objects.all()
        product_category = Product.objects.filter(category_id=pk)
        # paginator
        page = Paginator(product_category, 1)
        page_number = request.GET.get('page')

        product_category_page = page.page(page_number)

        # print(product_category)
        context = {
            'product_category_page': product_category_page,
            'Category_list': category_list,
            'cat_id': pk
        }
        return render(request, 'landing/product/List_product.html', context=context)


class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'Detail_product'
    # queryset = Product.objects.filter(id=pk)
    template_name = 'landing/product/Detail_view_product.html'


class add_to_OrderView(View):
    def post(self, request, pk):
        from product.Cart import Cart
        cart = Cart(request)
        cart.add(pk, request.POST['number'])
        # cart.__iter__()
        # print(len(cart))
        response = redirect('product:Detail_product', pk)
        response.set_cookie('count', len(cart))
        return response

templates/landing/product/Category.html
{% extends "landing/base/_base.html" %}
{% block title %} Category {% endblock %}
{% block content %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "landing/css/category.css" %}">
    <div class="container mt-1">
        {% for i in Category_list %}
            <div class="dropdown">
                {% if  i.category_root  == None %}
                    <p type="button" class=" dropdown-toggle" data-bs-toggle="dropdown">
                        {{ i.category_name }}</p>
                    <ul class="dropdown-menu">
                        {% for j in Category_list %}
                            {% if j.category_root == i %}
                                <li><a class="dropdown-item" href="{% url 'product:category_product' j.id%}" id="{{ j.category_name }}"
                                       data-id="{{ j.category_name }}">{{ j.category_name }}</a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/landing/product/Detail_view_product.html
{% extends "landing/base/_base.html" %}
{% block title %} Category {% endblock %}
{% load i18n %}
{% block content %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "landing/css/detail_product.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "landing/css/product.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "landing/css/category.css" %}">
    <div class="container">
        <div class="card">
            <div class="container-fliud">
                <div class="wrapper row">
                    <div class="preview col-md-6">
                        <div class="preview-pic tab-content">
                            <div class="tab-pane active" id="pic-1"><img src="{{ Detail_product.image.url }}"/></div>

                        </div>
                        <ul class="preview-thumbnail nav nav-tabs">
                            <li class="active"><a data-target="#pic-1" data-toggle="tab"><img
                                    src="{{ Detail_product.image.url }}"/></a></li>
                        </ul>

                    </div>
                    <div class="details col-md-6">
                        <h3 class="product-title">{{ Detail_product.name_product }}</h3>
                        <div class="rating">
                            <div class="stars">
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star checked"></span>
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                            </div>
                            <span class="review-no">{% trans '41 reviews' %}</span>
                        </div>
                        <p class="product-brand">{{ Detail_product.brand }}</p>
                        <p class="product-description">{{ Detail_product.descriptions }}</p>
                        <p class="number">{% trans 'number in shop:' %} <span>{{ Detail_product.number_store }} </span>
                        </p>
                        <h5 class="price">{% trans 'current price:' %}
                            <span>{{ Detail_product.price }} {% trans 'Rial' %}</span></h5>
                        <p class="vote">
                            <strong>{% trans '91%' %} </strong> {% trans 'of buyers enjoyed this product!' %}
                            <strong>{% trans '87 votes' %}</strong>
                        </p>
                        <div class="action">
                            {% csrf_token %}
                            <div class="qty mt-1 mb-2">
                                <span class="minus  btn-danger">-</span>
                                {#                                    <input type="number" class="add-to-cart count" name="number" value="1" min="1"#}
                                {#                                           max="{{ Detail_product.number_store }}">#}
                                <input type="number" id="number" class="count me-3 ms-3 btn-default" name="number"
                                       value="1"
                                       min="1"
                                       max="{{ Detail_product.number_store }}">

                                <span class="plus btn-success"
                                      onclick="plus({{ Detail_product.number_store }})">+</span>
                            </div>
                            <div class="mt-5">
                                <a href="{% url 'product:category_product' Detail_product.category_id %}?page=1"
                                   style="color: white;text-decoration: none">
                                    <div class="d-inline like btn btn-default w-40 mt-2"
                                    >{% trans 'back' %}</div>
                                </a>
                                <div class="d-inline add-to-cart btn btn-default fa-cart-plus w-40"
                                     onclick="add_product('{% url 'product:add_product' Detail_product.id %}',{{ Detail_product.id }});add_product_alert()"
                                >{% trans 'add to cart' %}</div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
        <script>
            $('.count').prop('disabled', true);

            function plus(max) {
                if (parseInt($('.count').val()) <= max-1) {
                    $('.count').val(parseInt($('.count').val()) + 1);
                }
            }

            $(document).on('click', '.minus', function () {
                $('.count').val(parseInt($('.count').val()) - 1);
                if ($('.count').val() == 0) {
                    $('.count').val(1);
                }
            });

            function add_product_alert() {
                Swal.fire({
                    icon: 'success',
                    title: 'product add to cart',
                    timer: 2000
                })
            }

            function add_product(url, id) {
                var number = $("#number").val();
                csrfmiddlewaretoken = $('input[name=csrfmiddlewaretoken]').val()
                var sendInfo = {
                    csrfmiddlewaretoken: csrfmiddlewaretoken,
                    id: id,
                    number: parseInt(number),
                };
                $.ajax({
                    type: "POST",
                    url: url,
                    dataType: "json",
                    headers: {
                        "X-CSRFToken": csrfmiddlewaretoken
                    },
                    success: () => {
                        alert("add to cart")
                        Swal.fire({
                            icon: 'success',
                            title: 'product add to cart',
                            timer: 10000
                        })
                    },
                    data: sendInfo
                });
            }
        </script>
{% endblock %}

templates/landing/product/List_product.html
{% extends "landing/product/Category.html" %}
{% block title %} product {% endblock %}
{% load i18n %}
{% block content %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "landing/css/product.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "landing/css/category.css" %}">
    <div class="container mt-1">
        {% for i in Category_list %}
            <div class="dropdown">
                {% if  i.category_root  == None %}
                    <p type="button" class=" dropdown-toggle" data-bs-toggle="dropdown">
                        {{ i.category_name }}</p>
                    <ul class="dropdown-menu">
                        {% for j in Category_list %}
                            {% if j.category_root == i %}
                                <li><a class="dropdown-item" href="{% url 'product:category_product' pk=j.id%}?page=1"
                                       id="{{ j.category_name }}"
                                       data-id="{{ j.category_name }}">{{ j.category_name }}</a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        {% endfor %}

    </div>
    <div class="container mt-3 mb-3 d-flex justify-content-center">
        <div class="row d-flex justify-content-center">
            {% for product in product_category_page.object_list %}
                <div class="card  m-2 " style="width: 15rem;">
                    <a href="{% url 'product:Detail_product' product.id %}">
                        <img src="{{ product.image.url }}" class="card-img-top" data-bs-toggle="modal"
                             data-bs-target="#{{ product.name_product }}"
                             alt="{{ product.name_product }}" width="350" height="200">
                    </a>
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name_product }}</h5>
                        <p class="card-text">{{ product.price }} {% trans 'Rial'%}</p>

                        <a class="btn btn-primary" href="{% url 'product:Detail_product' product.id %}">{% trans 'Detail products' %}
                            <i class="fa fa-info-circle  ml-2" aria-hidden="true"></i>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="inline mb-2 d-flex flex-row-reverse bd-highlight ">
        {% if product_category_page.has_next %}
                      <a href="{% url 'product:category_product' cat_id %}?page={{ product_category_page.next_page_number }}"
                         class="badge bg-primary text-wrap m-1 me-3"  style="text-decoration: none;">{% trans 'Next' %} &raquo;</a>
        {% endif %}
    {% if product_category_page.has_previous %}
                <a href="{% url 'product:category_product' cat_id %}?page={{ product_category_page.previous_page_number }}" class="badge bg-primary text-wrap m-1 me-3" style="text-decoration: none;">&laquo;
            {% trans 'Previous' %}</a>
    {% endif %}
    </div>
{% endblock %}